include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    unawaited_futures: true
    discarded_futures: true
    directives_ordering: true
    prefer_relative_imports: true
