name: flrogue
description: "An AI converted pyrogue version."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: monospace
      fonts:
        - asset: fonts/IBMPlexMono-Medium.ttf
